export default {
  topLevelIds: ['page1'],
  entities: {
    pages: {
      page1: {
        url: '',
        id: 'page1',
        title: 'Page 1 Title',
        level: 0,
        parentId: 'ij',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: ['page1-1', 'page1-2'],
      },
      'page1-1': {
        url: '',
        id: 'page1-1',
        title: 'Page 1-1 Title',
        level: 1,
        parentId: 'page1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: ['page1-1-1', 'page1-1-2'],
      },
      'page1-2': {
        url: '',
        id: 'page1-2',
        title: 'Page 1-2 Title',
        level: 1,
        parentId: 'page1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: [],
      },
      'page1-1-1': {
        url: '',
        id: 'page1-1-1',
        title: 'Page 1-1-1 Title',
        level: 2,
        parentId: 'page1-1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: [],
      },
      'page1-1-2': {
        url: '',
        id: 'page1-1-2',
        title: 'Page 1-1-2 Title',
        level: 2,
        parentId: 'page1-1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: ['page1-1-2-1'],
      },
      'page1-1-2-1': {
        url: '',
        id: 'page1-1-2-1',
        title: 'Page 1-1-2-1 Title',
        level: 3,
        parentId: 'page1-1-2',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: [],
      },
    },
  },
}
