export default {
  topLevelIds: ['page1', 'page2', 'page3', 'page4', 'page5'],
  entities: {
    pages: {
      page1: {
        url: '',
        id: 'page1',
        title: 'Page 1 Title',
        level: 0,
        parentId: 'ij',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: ['page1-1', 'page1-2'],
      },
      'page1-1': {
        url: '',
        id: 'page1-1',
        title: 'Page 1-1 Title',
        level: 1,
        parentId: 'page1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: ['page1-1-1', 'page1-1-2'],
      },
      'page1-2': {
        url: '',
        id: 'page1-2',
        title: 'Page 1-2 Title',
        level: 1,
        parentId: 'page1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: [],
      },
      'page1-1-1': {
        url: '',
        id: 'page1-1-1',
        title: 'Page 1-1-1 Title',
        level: 2,
        parentId: 'page1-1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: [],
      },
      'page1-1-2': {
        url: '',
        id: 'page1-1-2',
        title: 'Page 1-1-2 Title',
        level: 2,
        parentId: 'page1-1',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: ['page1-1-2-1'],
      },
      'page1-1-2-1': {
        url: '',
        id: 'page1-1-2-1',
        title: 'Page 1-1-2-1 Title',
        level: 3,
        parentId: 'page1-1-2',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: [],
      },
      page2: {
        url: '',
        id: 'page2',
        title: 'Page 2 Title',
        level: 0,
        parentId: 'root',
        tabIndex: 1,
        doNotShowWarningLink: true,
        pages: [],
      },
      page3: {
        url: '',
        id: 'page3',
        title: 'Page 3 Title',
        level: 0,
        parentId: 'root',
        tabIndex: 2,
        doNotShowWarningLink: true,
        pages: [],
      },
      page4: {
        url: '',
        id: 'page4',
        title: 'Page 4 Title',
        level: 0,
        parentId: 'ij',
        tabIndex: 3,
        doNotShowWarningLink: true,
        pages: ['page4-1'],
      },
      'page4-1': {
        url: '',
        id: 'page4-1',
        title: 'Page 4-1 Title',
        level: 1,
        parentId: 'page4',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: [],
      },
      page5: {
        url: '',
        id: 'page5',
        title: 'Page 5 Title',
        level: 0,
        parentId: 'ij',
        tabIndex: 4,
        doNotShowWarningLink: true,
        pages: ['page5-1', 'page5-2'],
      },
      'page5-1': {
        url: '',
        id: 'page5-1',
        title: 'Page 5-1 Title',
        level: 1,
        parentId: 'page5',
        tabIndex: 0,
        doNotShowWarningLink: true,
        pages: ['page-5-1-1'],
      },
      'page5-2': {
        url: '',
        id: 'page5-2',
        title: 'Page 5-2 Title',
        level: 1,
        parentId: 'page5',
        tabIndex: 1,
        doNotShowWarningLink: true,
        pages: [],
      },
      'page5-1-1': {
        url: '',
        id: 'page5-1-1',
        title: 'Page 5-1-1 Title',
        level: 2,
        parentId: 'page5-1',
        tabIndex: 5,
        doNotShowWarningLink: true,
        pages: [],
      },
    },
  },
}
